[phases.setup]
nixPkgs = ["nodejs-18"]

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"

[build.env]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
NEXT_TELEMETRY_DISABLED = "1"
