[phases.setup]
nixPkgs = ["python39"]

[phases.build]
cmd = "pip install -r requirements.txt"

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8000"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PORT = "8000"

[build.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PORT = "8000"
