[phases.setup]
nixPkgs = ["nodejs-18"]

[phases.build]
cmd = "npm run build"

[start]
cmd = "node dist/main.js"

[variables]
NODE_ENV = "production"
PORT = "3001"

[build.env]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"

[deploy.env]
NODE_ENV = "production"
PORT = "3001"
